name: Build Mod

on: [push, pull_request]

jobs:
  buildLib:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew :lib:deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: lib/build/libs/${{ github.event.repository.name }}.
    
  buildGenesis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew :genesis:deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: genesis/build/libs/${{ github.event.repository.name }}.jar
